# fastuma.conf
# ~/.local/share/fastuma/fastuma.conf

# Image module: outfit | card | icon | mini
RESOURCE=outfit

# Random character each run? true | false
RANDOM_CHARA=true

# Random outfit for the chosen character? true | false
RANDOM_OUTFIT=true

# Used only when RANDOM_CHARA=false
# Set to a chara_game_id from uma_grouped.json  e.g. 1015 TM Opera O
FIXED_CHARA_ID=1015

# Used only when RANDOM_OUTFIT=false
# 0 is usually the classic outfit, 1, 2, etc. for alternates
FIXED_OUTFIT_INDEX=0

# Your fastfetch base config (never modified directly)
FASTFETCH_CONFIG=~/.config/fastfetch/config.jsonc

# Image protocol: kitty | sixel | iterm2 | chafa
IMAGE_PROTOCOL=kitty